name: BuildTest
on: [push, pull_request]
jobs:
  build-job:
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11']
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: chmod +x ./gradlew && ./gradlew :test
